SET DATE TO dmy
SET DEFAULT TO SYS(5)+SYS(2003)
SET PATH TO
SET DELETED ON
SET SAFETY OFF
SET CENTURY on
SET EXCLUSIVE OFF
SET EXACT ON
SET SYSMENU off

_screen.windowstate= 2

DO FORM principal.scx
READ EVENTS

